# -*- mode: ruby -*-
# vi: set ft=ruby :

#const.
VAGRANTFILE_API_VERSION = "2"

remote_synced_folder_root = "/opt/kurento-elixir"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define :kurento_elixir do |kurento_elixir|
    kurento_elixir.vm.box = "ubuntu/trusty64"

    #kurento_elixir.vm.network :forwarded_port, guest: 80, host: 8080
    kurento_elixir.vm.network :private_network, ip: "192.168.66.11"
    #kurento_elixir.vm.network :public_network, :bridge => "en0: Wi-Fi (AirPort)", :ip => "#{ip_kurento_elixir}", :netmask => "255.255.255.0"

    kurento_elixir.vm.synced_folder "../../", "#{remote_synced_folder_root}"

    kurento_elixir.vm.provider :virtualbox do |vb|
       vb.gui = false
       ## Use VBoxManage to customize the VM. For example to change memory:
       #vb.customize ["modifyvm", :id, "--memory", "1024"]
       #vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
       #vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end

    kurento_elixir.vm.provision "ansible" do |ansible|
      ansible.playbook = "../provisioning/vagrant-local.yml"
      ansible.verbose = "v"
    end

  end
end
